<div class='footer' style='background:#544;padding:10px;color:#ddd'>
	<form class='col-xs-12'  action='search.php'>
			<table width='100%'><tr style='background:#ddd;border:1px solid #555;'><td width='80%'>
				<input class='special_input' name='term' style='height:30px' type='text'
				placeholder='Search'></td><td align='right'><button class='btn btn-danger'>Search</button></td></tr>
			</table>
	</form>

			<center><a class='text-muted' href="logout.php">Logout</a></center>
		</div>
	</body>
</html>
