<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1.0" />
		<meta name="description" content="Fueling social interaction between Nigerian Schools" />
		<meta name="author" content="Friday Godswill U" />
		<link rel='stylesheet' href='css/bootstrap.css' />
		<link rel='stylesheet' href='css/styles.css' />
		<link rel="shortcut icon" href="favicon.ico"/>
		<script type="text/javascript" src='js/jquery.js'></script>
		<script type="text/javascript" src='js/script.js'></script>
	</head>
	<body style='max-width:600px;margin:auto;background:#aaa;'>

	<script>
		var token = '<?php echo transform($_SESSION['user']); ?>'
		var user = '<?php echo $_SESSION['user'] ?>'
	</script>
	<style>
	*{
		font-family: "lucida grande",tahoma,verdana,arial,sans-serif;
	}
	</style>
