<?php
	define("SITE_NAME","trybezone");
	define("DATABASE","trybezone");
	define("DB_USERNAME","root");
	define("DB_PASSWORD","jamdat");
	define("HOST","localhost");
	define("ROOT",'http://localhost:8008');
	define("TESTING",1);
	define("DATABASE_ERROR_MSG","<div class='alert alert-warning'>Oops, it looks like we are having trouble connecting to our database. Please try again</div>");
	$super_relationships = array ("Single","Dating","Engaged","Married","Its Complicated");
?>
